import type { RiskLevel, CrimeStatus } from "@/types";

// ─── Filter Options ───────────────────────────────────────────────────────

export const CRIME_TYPES = [
  "Violent Crime",
  "Property Crime",
  "Cyber Crime",
  "Narcotics",
  "Financial Crime",
  "Anti-Terrorism",
  "Missing Person",
  "Traffic Offence",
];

export const DISTRICTS = [
  "Central Delhi",
  "South Delhi",
  "North Delhi",
  "Mumbai Suburban",
  "Mumbai City",
  "Bengaluru Urban",
  "Bengaluru Central",
  "Hyderabad",
  "Gurugram",
  "Noida",
  "Pune",
  "Chennai Central",
  "Kolkata",
  "Ahmedabad",
  "Jammu",
  "Ghaziabad",
];

// ─── FIR Type ─────────────────────────────────────────────────────────────

export interface MockFIR {
  id: string;
  firNumber: string;
  title: string;
  description: string;
  crimeType: string;
  riskLevel: RiskLevel;
  status: CrimeStatus;
  location: string;
  district: string;
  state: string;
  ps: string;
  assignedTo: string;
  rank: string;
  suspects: string[];
  victims: string[];
  evidence: string[];
  reportedAt: string;
  updatedAt: string;
  aiScore: number;
  aiSummary: string;
  tags: string[];
}

// ─── Mock FIRs ────────────────────────────────────────────────────────────

export const MOCK_FIRS: MockFIR[] = [
  {
    id: "fir-001",
    firNumber: "FIR-2024-00847",
    title: "Armed Robbery — Sadar Bazar Jewellery Shop",
    description:
      "3–4 armed suspects entered Ratan Jewellers at 11:30 AM, overpowered security, and fled with gold jewellery worth ₹48 lakhs. One guard sustained injuries. Suspects used a white Fortuner (DL-01-XX-4782).",
    crimeType: "Violent Crime",
    riskLevel: "critical",
    status: "investigating",
    location: "Ratan Jewellers, Sadar Bazar Market",
    district: "Central Delhi",
    state: "Delhi",
    ps: "PS Sadar Bazar",
    assignedTo: "SP Rajesh Kumar",
    rank: "Superintendent of Police",
    suspects: ["Unknown Male #1 (30–35 yrs)", "Unknown Male #2 (25–30 yrs)", "Rajan Mehta (suspected)"],
    victims: ["Suresh Gupta (shop owner)", "Ramesh (security guard, injured)"],
    evidence: ["CCTV footage (3 cameras)", "Vehicle tyre marks", "Witness statements (4)", "Fingerprints (partial)"],
    reportedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    aiScore: 94,
    aiSummary: "High probability match with Sadar Gang MO. Vehicle linked to 2 prior incidents. Recommend cross-referencing FIR-2023-00621 suspects immediately.",
    tags: ["gang-activity", "weapon-used", "high-value-theft"],
  },
  {
    id: "fir-002",
    firNumber: "FIR-2024-00841",
    title: "Coordinated Cyber Fraud — Banking Phishing Campaign",
    description:
      "Coordinated phishing attack targeting HDFC Bank customers via spoofed SMS and emails. Approximately 2,300 accounts compromised. Total estimated loss ₹1.2 Cr. Victims lured to fake portal.",
    crimeType: "Cyber Crime",
    riskLevel: "high",
    status: "investigating",
    location: "Online — Servers traced to Hyderabad & Bengaluru",
    district: "Mumbai Suburban",
    state: "Maharashtra",
    ps: "PS Cyber Crime Mumbai",
    assignedTo: "DySP Priya Sharma",
    rank: "Deputy Superintendent of Police",
    suspects: ["Cyber Syndicate — 3 known aliases"],
    victims: ["2,300 HDFC account holders"],
    evidence: ["Domain registration records", "Server logs", "Email headers", "Transaction records"],
    reportedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    aiScore: 87,
    aiSummary: "Attack pattern matches 2 previous phishing waves (Oct 2023, Feb 2024). Same hosting provider fingerprint detected. Network linked to Pune-based syndicate.",
    tags: ["phishing", "bank-fraud", "organized-cybercrime"],
  },
  {
    id: "fir-003",
    firNumber: "FIR-2024-00844",
    title: "Missing Child — AMBER Alert Activated",
    description:
      "8-year-old Ananya Singh (female) reported missing from Vasant Kunj D-block park at 4:15 PM. Last seen in a red dress near the park gate. AMBER alert activated. No ransom demand received yet.",
    crimeType: "Missing Person",
    riskLevel: "critical",
    status: "investigating",
    location: "Vasant Kunj D-Block Park, Gate No. 2",
    district: "South Delhi",
    state: "Delhi",
    ps: "PS Vasant Kunj",
    assignedTo: "SI Meena Rawat",
    rank: "Sub Inspector",
    suspects: ["Unknown individual (white car, partial plate DL-9C)"],
    victims: ["Ananya Singh, 8 yrs, Female"],
    evidence: ["CCTV (park entrance)", "Witness account (2 mothers)", "AMBER alert issued"],
    reportedAt: new Date(Date.now() - 72 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    aiScore: 91,
    aiSummary: "Pattern matches 3 prior child abduction cases in South Delhi (2023). AI recommends immediate check at railway stations, bus terminals, and known trafficking routes.",
    tags: ["child-safety", "amber-alert", "abduction-suspected"],
  },
  {
    id: "fir-004",
    firNumber: "FIR-2024-00835",
    title: "Narcotics Seizure — NH-48 Checkpoint",
    description:
      "Traffic patrol at NH-48 intercepted a truck (HR-55-AC-2231) carrying 12 kg of heroin concealed in a false floor compartment. Two suspects arrested on the spot. Contraband estimated value ₹6 Cr.",
    crimeType: "Narcotics",
    riskLevel: "high",
    status: "open",
    location: "NH-48 Toll Plaza, Manesar",
    district: "Gurugram",
    state: "Haryana",
    ps: "PS Manesar",
    assignedTo: "SI Amit Verma",
    rank: "Sub Inspector",
    suspects: ["Manoj Yadav (arrested)", "Ravi Sharma (arrested)"],
    victims: [],
    evidence: ["12 kg heroin (seized)", "Truck (HR-55-AC-2231)", "Mobile phones (2)", "Cash ₹85,000"],
    reportedAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    aiScore: 79,
    aiSummary: "Route matches known Punjab–Delhi narcotics corridor. Suspects linked to Arun Singh network. Full network analysis recommended.",
    tags: ["heroin", "drug-trafficking", "inter-state"],
  },
  {
    id: "fir-005",
    firNumber: "FIR-2024-00829",
    title: "Financial Fraud — Shell Company Network",
    description:
      "Bengaluru-based company director arrested for operating 7 shell companies and siphoning ₹42 Cr via fraudulent invoices over 3 years. ED referral recommended.",
    crimeType: "Financial Crime",
    riskLevel: "medium",
    status: "investigating",
    location: "Whitefield, Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    ps: "PS Whitefield",
    assignedTo: "DSP Kavitha Nair",
    rank: "Deputy Superintendent of Police",
    suspects: ["Harish Menon (arrested)", "CA Suresh Patel (absconding)"],
    victims: ["Investors (47 individuals)", "Government (tax fraud)"],
    evidence: ["Bank statements (7 accounts)", "Company registration docs", "Emails (1,200+)", "Chartered accountant records"],
    reportedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    aiScore: 71,
    aiSummary: "Shell company network analysis complete. 7 entities identified across Karnataka, Maharashtra, and Gujarat. ED notice recommended. AI confidence: 88%.",
    tags: ["shell-company", "money-laundering", "ed-referral"],
  },
  {
    id: "fir-006",
    firNumber: "FIR-2024-00821",
    title: "Chain Snatching — Brigade Road",
    description:
      "Two bike-borne suspects snatched gold chain (85 grams) from a 62-year-old woman near Brigade Road Signal. Victim sustained minor injuries after being dragged. Suspects fled on a red Pulsar.",
    crimeType: "Property Crime",
    riskLevel: "medium",
    status: "open",
    location: "Brigade Road Signal, Near Barton Centre",
    district: "Bengaluru Central",
    state: "Karnataka",
    ps: "PS Brigade Road",
    assignedTo: "ASI Suresh Babu",
    rank: "Assistant Sub Inspector",
    suspects: ["Unknown Male on red Pulsar (KA-02-XX-8821)"],
    victims: ["Kamala Devi, 62 yrs, Female (minor injuries)"],
    evidence: ["CCTV footage (traffic camera)", "Witness statement (1)"],
    reportedAt: new Date(Date.now() - 18 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    aiScore: 55,
    aiSummary: "Bike description matches 4 prior chain snatchings in MG Road area. Recommend CCTV sweep of Brigade Road–MG Road corridor.",
    tags: ["chain-snatching", "bike-borne", "senior-victim"],
  },
  {
    id: "fir-007",
    firNumber: "FIR-2024-00814",
    title: "Vehicle Theft — Hitech City Parking Complex",
    description:
      "Honda City (TS-09-EG-7721) stolen from Level 3 of Hitech City Mall parking between 2:00 PM and 6:00 PM. Owner reported car missing when returning from office.",
    crimeType: "Property Crime",
    riskLevel: "low",
    status: "open",
    location: "Hitech City Mall Parking, Level 3",
    district: "Hyderabad",
    state: "Telangana",
    ps: "PS Hitech City",
    assignedTo: "HC Ramesh Rao",
    rank: "Head Constable",
    suspects: ["Unknown"],
    victims: ["Vikram Reddy (vehicle owner)"],
    evidence: ["Parking ticket", "CCTV (limited coverage)", "Broken window glass"],
    reportedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 3600000).toISOString(),
    aiScore: 32,
    aiSummary: "Low AI priority. No pattern match with known auto-theft gangs. Standard investigation protocol recommended.",
    tags: ["vehicle-theft", "parking"],
  },
  {
    id: "fir-008",
    firNumber: "FIR-2024-00798",
    title: "Drug Peddling Network — Micro Delivery Operation",
    description:
      "Multi-month intelligence-led operation uncovering a micro-delivery drug network operating via encrypted messaging app. 12 peddlers arrested, 4 kg of MDMA and cannabis seized.",
    crimeType: "Narcotics",
    riskLevel: "high",
    status: "investigating",
    location: "Koregaon Park, Pune",
    district: "Pune",
    state: "Maharashtra",
    ps: "PS Koregaon Park",
    assignedTo: "DSP Ravi Patil",
    rank: "Deputy Superintendent of Police",
    suspects: ["Arun Singh (kingpin — absconding)", "12 peddlers (arrested)"],
    victims: [],
    evidence: ["Mobile phones (14)", "Drugs (4 kg MDMA + cannabis)", "Cash ₹3.2 lakh", "Ledger records"],
    reportedAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    aiScore: 88,
    aiSummary: "Network linked to Arun Singh syndicate. Cross-state connections to Mumbai, Goa, and Bengaluru detected. AI recommends joint NCB–State Police operation.",
    tags: ["mdma", "drug-network", "encrypted-comms", "arun-singh"],
  },
  {
    id: "fir-009",
    firNumber: "FIR-2024-00785",
    title: "ATM Skimming Gang — Multi-location Operation",
    description:
      "Skimming devices discovered at 7 ATMs across Pune over 3 weeks. Identical device model (custom-built) installed. ₹18 lakh fraudulently withdrawn from 142 accounts before detection.",
    crimeType: "Cyber Crime",
    riskLevel: "high",
    status: "investigating",
    location: "Multiple ATMs across Pune City",
    district: "Pune",
    state: "Maharashtra",
    ps: "PS Cyber Crime Pune",
    assignedTo: "PI Anjali Deshmukh",
    rank: "Police Inspector",
    suspects: ["Eastern European Gang (2 suspects — absconding)", "Local handler (1 arrested)"],
    victims: ["142 account holders"],
    evidence: ["7 skimming devices", "Card data (142 accounts)", "ATM CCTV footage", "Arrested handler mobile"],
    reportedAt: new Date(Date.now() - 72 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    aiScore: 83,
    aiSummary: "Device fingerprint matches ATM skimming cases in Bengaluru (Aug 2023) and Delhi (Nov 2023). Same gang suspected. Interpol Red Notice recommended.",
    tags: ["atm-skimming", "organized", "interpol"],
  },
  {
    id: "fir-010",
    firNumber: "FIR-2024-00771",
    title: "Terrorist Threat — IED Hoax, Railway Station",
    description:
      "Anonymous call received at Jammu Railway Station reporting an IED. Full evacuation conducted. Bomb squad cleared the premises after 3-hour sweep. No device found. Call traced to prepaid SIM.",
    crimeType: "Anti-Terrorism",
    riskLevel: "critical",
    status: "investigating",
    location: "Jammu Tawi Railway Station, Platform 3",
    district: "Jammu",
    state: "Jammu & Kashmir",
    ps: "Railway Police Jammu",
    assignedTo: "SP Vikram Singh",
    rank: "Superintendent of Police",
    suspects: ["Unknown — prepaid SIM (traced to Ludhiana)"],
    victims: ["General public (2,400+ evacuated)"],
    evidence: ["Call recording", "Prepaid SIM data", "Station CCTV (240 cameras)"],
    reportedAt: new Date(Date.now() - 96 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    aiScore: 76,
    aiSummary: "SIM purchase location (Ludhiana) matches 2 prior hoax calls at Delhi airports. NIA loop-in recommended. Pattern suggests psychological disruption campaign.",
    tags: ["hoax-call", "ied-threat", "railway", "nia"],
  },
  {
    id: "fir-011",
    firNumber: "FIR-2024-00763",
    title: "Murder — Body Found in Abandoned Warehouse",
    description:
      "Decomposed body of male (40–50 yrs) found by workers in an abandoned warehouse. Multiple stab wounds. Victim not yet identified. Forensic team deployed.",
    crimeType: "Violent Crime",
    riskLevel: "critical",
    status: "investigating",
    location: "Abandoned Warehouse, Phase 2 Industrial Area, Noida",
    district: "Noida",
    state: "Uttar Pradesh",
    ps: "PS Phase 2 Noida",
    assignedTo: "CO Ajay Tomar",
    rank: "Circle Officer",
    suspects: ["Unknown"],
    victims: ["Unidentified Male (40–50 yrs)"],
    evidence: ["DNA samples", "Fingerprints", "Stab wound forensics", "Security footage (nearby area)"],
    reportedAt: new Date(Date.now() - 36 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    aiScore: 85,
    aiSummary: "Victim profile pending ID. Area known for gang activity. AI cross-referencing missing persons database. 3 potential matches found.",
    tags: ["murder", "unidentified-victim", "gang-suspected"],
  },
  {
    id: "fir-012",
    firNumber: "FIR-2024-00751",
    title: "Extortion — Death Threats to Businessman",
    description:
      "Mumbai-based garment exporter Rakesh Agarwal received repeated threats via calls and messages demanding ₹2 Cr. Threatener claims to be associated with an underworld group.",
    crimeType: "Violent Crime",
    riskLevel: "high",
    status: "investigating",
    location: "Dharavi, Mumbai (victim's factory)",
    district: "Mumbai City",
    state: "Maharashtra",
    ps: "PS Dharavi",
    assignedTo: "PI Fatima Sheikh",
    rank: "Police Inspector",
    suspects: ["Voice matches known extortionist Salim Qureshi (absconding)"],
    victims: ["Rakesh Agarwal (businessman)"],
    evidence: ["Call recordings (12)", "WhatsApp messages", "Voice sample for analysis"],
    reportedAt: new Date(Date.now() - 60 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    aiScore: 74,
    aiSummary: "Voice analysis 73% match with Salim Qureshi. Subject has 3 prior extortion cases. Lookout notice recommended. Victim requires security detail.",
    tags: ["extortion", "underworld", "threat"],
  },
  {
    id: "fir-013",
    firNumber: "FIR-2024-00738",
    title: "Document Forgery — Fake Property Papers",
    description:
      "Property dispute revealed forged registration documents for a ₹3.5 Cr property in South Kolkata. Original owner filed complaint. Sub-registrar office seal was duplicated.",
    crimeType: "Financial Crime",
    riskLevel: "medium",
    status: "closed",
    location: "Ballygunge, South Kolkata",
    district: "Kolkata",
    state: "West Bengal",
    ps: "PS Ballygunge",
    assignedTo: "SI Tanmoy Das",
    rank: "Sub Inspector",
    suspects: ["Bimal Roy (arrested · chargesheet filed)"],
    victims: ["Sudhir Ghosh (property owner)"],
    evidence: ["Forged documents (original + fake)", "Registrar records", "Handwriting analysis", "Witness (1)"],
    reportedAt: new Date(Date.now() - 120 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 96 * 3600000).toISOString(),
    aiScore: 45,
    aiSummary: "Case closed. Chargesheet filed. Suspect arrested. Property dispute under civil court jurisdiction.",
    tags: ["forgery", "property-fraud", "chargesheet-filed"],
  },
  {
    id: "fir-014",
    firNumber: "FIR-2024-00725",
    title: "Hit and Run — Pedestrian Fatality on Ring Road",
    description:
      "Elderly pedestrian (72 yrs) struck by speeding vehicle on Outer Ring Road at 11:45 PM. Victim died en route to hospital. Vehicle fled. Tyre marks and paint fragments recovered.",
    crimeType: "Traffic Offence",
    riskLevel: "high",
    status: "open",
    location: "Outer Ring Road, Near Sarita Vihar Metro",
    district: "South Delhi",
    state: "Delhi",
    ps: "PS Sarita Vihar",
    assignedTo: "SI Prakash Mehra",
    rank: "Sub Inspector",
    suspects: ["Unknown vehicle — dark coloured SUV"],
    victims: ["Ramji Lal (72 yrs, deceased)"],
    evidence: ["Tyre marks", "Paint fragments (silver/grey)", "CCTV (partial, low quality)", "Post-mortem report"],
    reportedAt: new Date(Date.now() - 84 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 3600000).toISOString(),
    aiScore: 62,
    aiSummary: "Paint analysis: likely Honda CRV or Hyundai Creta (silver/grey, 2019–2022). AI recommends checking toll cameras on NH-44 corridor.",
    tags: ["hit-run", "fatality", "traffic"],
  },
  {
    id: "fir-015",
    firNumber: "FIR-2024-00712",
    title: "Organised Gambling Den Raid — Ahmedabad",
    description:
      "Night raid on illegal casino operating in a luxury apartment. 47 persons detained. Cash ₹28 lakh, betting chips, and multiple mobile phones seized. IPL betting suspected.",
    crimeType: "Financial Crime",
    riskLevel: "medium",
    status: "open",
    location: "SG Highway Residential Complex, Ahmedabad",
    district: "Ahmedabad",
    state: "Gujarat",
    ps: "PS SG Highway",
    assignedTo: "PI Hemant Joshi",
    rank: "Police Inspector",
    suspects: ["Vikram Shah (organiser — arrested)", "46 others (detained)"],
    victims: [],
    evidence: ["Cash ₹28 lakh", "Betting ledgers", "Phones (47)", "Video evidence"],
    reportedAt: new Date(Date.now() - 144 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 120 * 3600000).toISOString(),
    aiScore: 48,
    aiSummary: "Betting pattern suggests inter-state syndicate. Financial intelligence unit referral recommended for money trail.",
    tags: ["gambling", "ipl-betting", "organised-crime"],
  },
];
